const mongoose = require('mongoose');
const Rule = require('../models/Rule');

const centralRules = [
  {
    ruleId: 'RULE-06-1-A',
    ruleNumber: 'Rule 6(1)(a)',
    title: 'Rule 6(1)(a): Manufacturer/Packer Address',
    description: 'Name and complete address of the manufacturer, packer, or importer must be declared.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_a'
  },
  {
    ruleId: 'RULE-06-1-B',
    ruleNumber: 'Rule 6(1)(b)',
    title: 'Rule 6(1)(b): Generic or Common Name',
    description: 'Common or generic name of the commodity must be declared prominently on the package.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_b'
  },
  {
    ruleId: 'RULE-06-1-C',
    ruleNumber: 'Rule 6(1)(c)',
    title: 'Rule 6(1)(c): Net Quantity Declaration',
    description: 'Net quantity in terms of standard metric weight, measure, or number must be stated.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_c'
  },
  {
    ruleId: 'RULE-06-1-D',
    ruleNumber: 'Rule 6(1)(d)',
    title: 'Rule 6(1)(d): Month & Year of Manufacture/Packing',
    description: 'Month and year in which the commodity is manufactured, packed, or imported must be declared.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_d'
  },
  {
    ruleId: 'RULE-06-1-DA',
    ruleNumber: 'Rule 6(1)(da)',
    title: 'Rule 6(1)(da): Unit Sale Price (USP)',
    description: 'Unit Sale Price per g/kg/ml/L or piece must be declared on commodities sold by mass/volume or multi-piece packs.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2022-12-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2022',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2022.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule06_1_da'
  },
  {
    ruleId: 'RULE-06-1-E',
    ruleNumber: 'Rule 6(1)(e)',
    title: 'Rule 6(1)(e): Retail Sale Price (MRP)',
    description: 'Maximum Retail Price (MRP) inclusive of all taxes must be declared clearly with currency symbol.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_e'
  },
  {
    ruleId: 'RULE-06-1-F',
    ruleNumber: 'Rule 6(1)(f)',
    title: 'Rule 6(1)(f): Sizes and Dimensions',
    description: 'Dimensions, size or measurement of the commodity must be declared where size is relevant (e.g. garments, bedsheets).',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule06_1_f'
  },
  {
    ruleId: 'RULE-06-1-G',
    ruleNumber: 'Rule 6(1)(g)',
    title: 'Rule 6(1)(g): Country of Origin',
    description: 'Country of origin or manufacture must be explicitly declared on imported and domestic goods.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2017-06-23'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2017.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule06_1_g'
  },
  {
    ruleId: 'RULE-06-2',
    ruleNumber: 'Rule 6(2)',
    title: 'Rule 6(2): Consumer Care Details',
    description: 'Name, address, telephone number, and email address of the person or office to contact for consumer complaints.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_2'
  },
  {
    ruleId: 'RULE-08',
    ruleNumber: 'Rule 8',
    title: 'Rule 8: Principal Display Panel Readability',
    description: 'Declarations on the principal display panel must be legible, prominent, and conspicuous.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule08'
  },
  {
    ruleId: 'RULE-09',
    ruleNumber: 'Rule 9',
    title: 'Rule 9: Font Height Standards',
    description: 'Declarations of quantity must satisfy minimum statutory numeral font height prescribed under Table 1.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule09'
  },
  {
    ruleId: 'RULE-10',
    ruleNumber: 'Rule 10',
    title: 'Rule 10: E-Commerce Declarations',
    description: 'Statutory declarations must be displayed on marketplace e-commerce platforms before sale.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2018-01-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2018.1',
    weight: 5,
    severity: 'LOW',
    evaluatorKey: 'rule10'
  },
  {
    ruleId: 'RULE-12-6',
    ruleNumber: 'Rule 12(6)',
    title: 'Rule 12(6): Prohibited Misleading Words',
    description: 'No qualifying words like "jumbo", "extra", "average", "approximately" shall be used with quantity declarations.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule12_6'
  },
  {
    ruleId: 'RULE-13',
    ruleNumber: 'Rule 13',
    title: 'Rule 13: Standard Metric Units',
    description: 'Quantities must be declared in prescribed SI metric units (kg, g, mg, L, ml, m, cm, mm, N).',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2011.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule13'
  }
];

const stateRules = [
  // TELANGANA
  {
    ruleId: 'TS-ENF-07',
    ruleNumber: 'Rule 7',
    title: 'State Packer Registration (Telangana)',
    description: 'Every manufacturer or packer operating in or distributing packages within Telangana must be registered with the Controller of Legal Metrology, Government of Telangana under Section 19 of the Act.',
    jurisdiction: 'State',
    stateName: 'Telangana',
    productCategory: 'All',
    effectiveFrom: new Date('2014-06-02'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Telangana Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://clm.telangana.gov.in/rules-and-acts',
    lastVerifiedDate: new Date('2024-02-01'),
    version: '2014.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration'
  },
  {
    ruleId: 'TS-ENF-04',
    ruleNumber: 'Rule 4(1)',
    title: 'Packaging Verification & Stamping (Telangana)',
    description: 'Weighing and measuring instruments used in packaging within Telangana jurisdiction must hold a valid certificate of verification from a designated Telangana Legal Metrology Inspector.',
    jurisdiction: 'State',
    stateName: 'Telangana',
    productCategory: 'All',
    effectiveFrom: new Date('2014-06-02'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Telangana Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://clm.telangana.gov.in/rules-and-acts',
    lastVerifiedDate: new Date('2024-02-01'),
    version: '2014.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'state_verification_stamping'
  },
  {
    ruleId: 'TS-ENF-14',
    ruleNumber: 'Rule 14',
    title: 'Consumer Redressal & Inspection Log (Telangana)',
    description: 'Packaged commodity distributors in Telangana must maintain records of compliance inspection and provide accessible consumer grievance contact details.',
    jurisdiction: 'State',
    stateName: 'Telangana',
    productCategory: 'All',
    effectiveFrom: new Date('2014-06-02'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Telangana Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://clm.telangana.gov.in/rules-and-acts',
    lastVerifiedDate: new Date('2024-02-01'),
    version: '2014.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'state_consumer_redressal'
  },

  // MAHARASHTRA
  {
    ruleId: 'MH-ENF-05',
    ruleNumber: 'Rule 5',
    title: 'Packer Registration under Controller (Maharashtra)',
    description: 'Mandatory registration of manufacturer, packer, or importer with the Controller of Legal Metrology, Maharashtra State, prior to commercial distribution.',
    jurisdiction: 'State',
    stateName: 'Maharashtra',
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Maharashtra Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://legalmetrology.maharashtra.gov.in',
    lastVerifiedDate: new Date('2024-01-20'),
    version: '2011.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration'
  },
  {
    ruleId: 'MH-ENF-08',
    ruleNumber: 'Rule 8',
    title: 'Verification Stamping by Inspector (Maharashtra)',
    description: 'Requirement of periodic state stamping and verification compliance for packaging measurement equipment in Maharashtra.',
    jurisdiction: 'State',
    stateName: 'Maharashtra',
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Maharashtra Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://legalmetrology.maharashtra.gov.in',
    lastVerifiedDate: new Date('2024-01-20'),
    version: '2011.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'state_verification_stamping'
  },

  // KARNATAKA
  {
    ruleId: 'KA-ENF-07',
    ruleNumber: 'Rule 7',
    title: 'State Packer Registration (Karnataka)',
    description: 'Registration of every packaging entity with the Department of Legal Metrology, Government of Karnataka.',
    jurisdiction: 'State',
    stateName: 'Karnataka',
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Karnataka Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://clm.karnataka.gov.in',
    lastVerifiedDate: new Date('2024-01-25'),
    version: '2011.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration'
  },
  {
    ruleId: 'KA-ENF-04',
    ruleNumber: 'Rule 4',
    title: 'Measurement Verification Certificate (Karnataka)',
    description: 'Mandatory verification of net quantity batching devices by Karnataka Legal Metrology enforcement officers.',
    jurisdiction: 'State',
    stateName: 'Karnataka',
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Karnataka Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://clm.karnataka.gov.in',
    lastVerifiedDate: new Date('2024-01-25'),
    version: '2011.1',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'state_verification_stamping'
  },

  // TAMIL NADU
  {
    ruleId: 'TN-ENF-06',
    ruleNumber: 'Rule 6',
    title: 'Controller Registration (Tamil Nadu)',
    description: 'Mandatory registration with the Controller of Legal Metrology, Labour and Employment Department, Tamil Nadu.',
    jurisdiction: 'State',
    stateName: 'Tamil Nadu',
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Tamil Nadu Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://labour.tn.gov.in/legal-metrology',
    lastVerifiedDate: new Date('2024-01-10'),
    version: '2011.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration'
  },

  // DELHI (NCT)
  {
    ruleId: 'DL-ENF-05',
    ruleNumber: 'Rule 5',
    title: 'Packer Registration (NCT of Delhi)',
    description: 'Registration of packers and manufacturers with the Controller of Legal Metrology, Government of NCT of Delhi.',
    jurisdiction: 'State',
    stateName: 'Delhi',
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Delhi Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://delhi.gov.in/legal-metrology',
    lastVerifiedDate: new Date('2024-01-18'),
    version: '2011.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration'
  },

  // GUJARAT
  {
    ruleId: 'GJ-ENF-07',
    ruleNumber: 'Rule 7',
    title: 'Packer Registration under Gujarat Enforcement',
    description: 'Registration of packers and manufacturers under the Controller of Legal Metrology, Government of Gujarat.',
    jurisdiction: 'State',
    stateName: 'Gujarat',
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Gujarat Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://consumer.gujarat.gov.in',
    lastVerifiedDate: new Date('2024-01-12'),
    version: '2011.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration'
  }
];

const seedRules = async () => {
  try {
    const allRules = [...centralRules, ...stateRules];
    let inserted = 0;
    let updated = 0;

    for (const rule of allRules) {
      const res = await Rule.findOneAndUpdate(
        { ruleId: rule.ruleId },
        { $set: rule },
        { upsert: true, new: true }
      );
      if (res) updated++;
    }

    console.log(`Rules seeded successfully: ${allRules.length} rules verified (Central & State).`);
    return { success: true, count: allRules.length };
  } catch (err) {
    console.error('Failed to seed rules:', err);
    throw err;
  }
};

module.exports = {
  seedRules,
  centralRules,
  stateRules
};
