const mongoose = require('mongoose');
const Rule = require('../models/Rule');
const RuleVersion = require('../models/RuleVersion');

// 1. Central Rules Master List (Baseline Active Definitions)
const centralRules = [
  {
    ruleId: 'RULE-06-1-A',
    ruleNumber: 'Rule 6(1)(a)',
    title: 'Rule 6(1)(a): Manufacturer/Packer Address',
    description: 'Name and complete physical premises address of manufacturer, packer, or importer must be declared.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2017-06-23'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_a',
    approvalStatus: 'Approved',
    approvedBy: 'Joint Secretary (Consumer Affairs), Govt of India',
    approvedDate: new Date('2017-06-23'),
    amendments: 'Amended via G.S.R. 629(E) mandating full premises details, state, and PIN code'
  },
  {
    ruleId: 'RULE-06-1-B',
    ruleNumber: 'Rule 6(1)(b)',
    title: 'Rule 6(1)(b): Generic or Common Name',
    description: 'Common or generic name of the commodity must be declared prominently on the package.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_b',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology, Ministry of Consumer Affairs',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Original enactment under Legal Metrology Act, 2009'
  },
  {
    ruleId: 'RULE-06-1-C',
    ruleNumber: 'Rule 6(1)(c)',
    title: 'Rule 6(1)(c): Net Quantity Declaration',
    description: 'Net quantity in terms of standard metric weight, measure, or number must be stated with minimum font height matrix.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2022-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2021',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2.0',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_c',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology, Government of India',
    approvedDate: new Date('2021-11-02'),
    amendments: 'Amended via G.S.R. 779(E) mandating Schedule II font area ratio'
  },
  {
    ruleId: 'RULE-06-1-D',
    ruleNumber: 'Rule 6(1)(d)',
    title: 'Rule 6(1)(d): Month & Year of Manufacture/Packing',
    description: 'Month and year in which commodity is manufactured, packed, or imported must be declared in standard MM/YYYY format.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_d',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Statutory enactment under Rule 6(1)(d)'
  },
  {
    ruleId: 'RULE-06-1-DA',
    ruleNumber: 'Rule 6(1)(da)',
    title: 'Rule 6(1)(da): Unit Sale Price (USP)',
    description: 'Unit Sale Price per g/kg/ml/L or piece must be declared on commodities sold by mass/volume or multi-piece packs.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2021-11-01'),
    effectiveTo: new Date('2026-12-31'),
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2021',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2.0',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule06_1_da',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology, Government of India',
    approvedDate: new Date('2021-11-02'),
    amendments: 'Amended via G.S.R. 779(E) dated 02.11.2021 mandating USP per g/ml or per piece'
  },
  {
    ruleId: 'RULE-06-1-E',
    ruleNumber: 'Rule 6(1)(e)',
    title: 'Rule 6(1)(e): Maximum Retail Price (MRP)',
    description: 'Retail sale price must be stated as "MRP ₹ xx.xx (inclusive of all taxes)". Dual MRP declaration is prohibited.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2018-01-01'),
    effectiveTo: new Date('2026-12-31'),
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2.0',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_e',
    approvalStatus: 'Approved',
    approvedBy: 'Joint Secretary (Legal Metrology)',
    approvedDate: new Date('2017-06-23'),
    amendments: 'Amended via G.S.R. 629(E) strictly prohibiting dual pricing and mandating ₹ symbol'
  },
  {
    ruleId: 'RULE-06-1-F',
    ruleNumber: 'Rule 6(1)(f)',
    title: 'Rule 6(1)(f): Dimensions Declaration',
    description: 'Dimensions of commodities sold by size (e.g. textiles, sheets) must be declared with length and width in cm/m.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'Apparel & Textiles',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule06_1_f',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Schedule III dimensions standard'
  },
  {
    ruleId: 'RULE-06-1-G',
    ruleNumber: 'Rule 6(1)(g)',
    title: 'Rule 6(1)(g): Country of Origin',
    description: 'Country of origin or manufacture must be declared on packages, especially mandatory for all imported goods.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2017-06-23'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.1',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_g',
    approvalStatus: 'Approved',
    approvedBy: 'Joint Secretary (Consumer Affairs)',
    approvedDate: new Date('2017-06-23'),
    amendments: 'Amended via G.S.R. 629(E) for imported pre-packaged goods'
  },
  {
    ruleId: 'RULE-06-2',
    ruleNumber: 'Rule 6(2)',
    title: 'Rule 6(2): Consumer Care Details',
    description: 'Name, address, telephone number, and email address of grievance person/office must be declared.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_2',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Statutory consumer grievance mechanism under Rule 6(2)'
  },
  {
    ruleId: 'RULE-08',
    ruleNumber: 'Rule 8',
    title: 'Rule 8: Principal Display Panel (PDP)',
    description: 'All mandatory declarations must appear on the Principal Display Panel (PDP) and not scattered obscurely.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule08',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Rule 8 PDP grouping standard'
  },
  {
    ruleId: 'RULE-09',
    ruleNumber: 'Rule 9',
    title: 'Rule 9: Minimum Font Size of Declarations',
    description: 'Height of letters and numerals must conform to Schedule II based on Principal Display Panel area.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule09',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Schedule II font size specifications'
  },
  {
    ruleId: 'RULE-10',
    ruleNumber: 'Rule 10',
    title: 'Rule 10: E-Commerce Marketplace Declarations',
    description: 'Digital marketplaces must display all mandatory declarations on product listings prior to purchase.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2017-06-23'),
    effectiveTo: new Date('2026-12-31'),
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule10',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2017-06-23'),
    amendments: 'Introduced vide G.S.R. 629(E) dated 23.06.2017 for digital platforms'
  },
  {
    ruleId: 'RULE-12-6',
    ruleNumber: 'Rule 12(6)',
    title: 'Rule 12(6): Prohibition of Misleading Words',
    description: 'No misleading exaggerations (e.g. jumbo, giant, full, jumbo pack) are permitted alongside net quantity.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 10,
    severity: 'HIGH',
    evaluatorKey: 'rule12_6',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Rule 12(6) deceptive trade practice restriction'
  },
  {
    ruleId: 'RULE-13',
    ruleNumber: 'Rule 13',
    title: 'Rule 13: Standard Metric Units',
    description: 'Symbols or units must conform strictly to SI metric standards (g, kg, mL, L, m, cm). Non-metric units prohibited.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule13',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2011-03-01'),
    amendments: 'First Schedule standard units of mass and volume'
  }
];

// 2. State-Specific Enforcement Rules Master List
const stateRules = [
  // Telangana
  {
    ruleId: 'TS-ENF-07',
    ruleNumber: 'Rule 7(1)',
    title: 'Packer Registration under Controller (Telangana)',
    description: 'Every manufacturer or packer of pre-packaged commodities operating within Telangana must obtain Registration under Rule 7.',
    jurisdiction: 'State',
    stateName: 'Telangana',
    productCategory: 'All',
    effectiveFrom: new Date('2024-01-01'),
    effectiveTo: new Date('2026-12-31'),
    status: 'Active',
    sourceDocument: 'Telangana Legal Metrology (Enforcement) Rules, 2015 & TS-iPASS Circular',
    sourceUrl: 'https://tsconsumeraffairs.telangana.gov.in/legal-metrology.jsp',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '2.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Govt of Telangana',
    approvedDate: new Date('2023-12-15'),
    amendments: 'G.O.Ms.No. 18 Consumer Affairs & Legal Metrology Dept dated 15.12.2023 transitioning to TS-iPASS'
  },
  {
    ruleId: 'TS-ENF-04',
    ruleNumber: 'Rule 4(1)',
    title: 'Verification & Stamping of Packaging Equipment (Telangana)',
    description: 'Packaging instruments and batch checkweighers in Telangana premises must bear valid annual stamping.',
    jurisdiction: 'State',
    stateName: 'Telangana',
    productCategory: 'All',
    effectiveFrom: new Date('2015-06-02'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Telangana Legal Metrology (Enforcement) Rules, 2015',
    sourceUrl: 'https://tsconsumeraffairs.telangana.gov.in/legal-metrology.jsp',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'state_verification_stamping',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Govt of Telangana',
    approvedDate: new Date('2015-06-02'),
    amendments: 'State enactment under Section 24 of Legal Metrology Act, 2009'
  },
  {
    ruleId: 'TS-ENF-14',
    ruleNumber: 'Rule 14(2)',
    title: 'State Consumer Redressal Cell Details (Telangana)',
    description: 'Packaged commodities marketed in Telangana must provide designated state consumer redressal contact.',
    jurisdiction: 'State',
    stateName: 'Telangana',
    productCategory: 'All',
    effectiveFrom: new Date('2019-03-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Telangana Consumer Protection & Legal Metrology Enforcement Directives',
    sourceUrl: 'https://tsconsumeraffairs.telangana.gov.in/legal-metrology.jsp',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.2',
    weight: 10,
    severity: 'LOW',
    evaluatorKey: 'state_consumer_redressal',
    approvalStatus: 'Approved',
    approvedBy: 'Joint Controller (Enforcement), Telangana',
    approvedDate: new Date('2019-02-15'),
    amendments: 'State Redressal Helpline linkage order'
  },

  // Maharashtra
  {
    ruleId: 'MH-ENF-05',
    ruleNumber: 'Rule 5(1)',
    title: 'Packer Registration under Controller (Maharashtra)',
    description: 'Packers and manufacturers in Maharashtra must hold active registration with the Controller of Legal Metrology, Mumbai.',
    jurisdiction: 'State',
    stateName: 'Maharashtra',
    productCategory: 'All',
    effectiveFrom: new Date('2011-09-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Maharashtra Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://legalmetrology.maharashtra.gov.in',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Maharashtra',
    approvedDate: new Date('2011-08-20'),
    amendments: 'Maharashtra Enforcement Rules, 2011 Notification'
  },
  {
    ruleId: 'MH-ENF-08',
    ruleNumber: 'Rule 8(3)',
    title: 'Verification Stamping by Inspector (Maharashtra)',
    description: 'Annual verification and stamping of filling and packaging machines by local Legal Metrology Inspector in Maharashtra.',
    jurisdiction: 'State',
    stateName: 'Maharashtra',
    productCategory: 'All',
    effectiveFrom: new Date('2011-09-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Maharashtra Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://legalmetrology.maharashtra.gov.in',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'state_verification_stamping',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Maharashtra',
    approvedDate: new Date('2011-08-20'),
    amendments: 'Inspector stamping verification guidelines'
  },

  // Karnataka
  {
    ruleId: 'KA-ENF-06',
    ruleNumber: 'Rule 6',
    title: 'Packer & Manufacturer Registration (Karnataka)',
    description: 'Mandatory certificate of registration issued by Controller of Legal Metrology, Bengaluru for packaged goods.',
    jurisdiction: 'State',
    stateName: 'Karnataka',
    productCategory: 'All',
    effectiveFrom: new Date('2011-10-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Karnataka Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://clm.karnataka.gov.in',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Karnataka',
    approvedDate: new Date('2011-09-15'),
    amendments: 'Rule 6 Registration mandate'
  },
  {
    ruleId: 'KA-ENF-09',
    ruleNumber: 'Rule 9',
    title: 'Mandatory Kannada Regional Language Labeling (Karnataka)',
    description: 'Goods pre-packaged and sold at retail points in Karnataka should optionally include consumer information in Kannada.',
    jurisdiction: 'State',
    stateName: 'Karnataka',
    productCategory: 'All',
    effectiveFrom: new Date('2018-05-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Karnataka Consumer Welfare & Metrology Advisory Circular',
    sourceUrl: 'https://clm.karnataka.gov.in',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.1',
    weight: 10,
    severity: 'LOW',
    evaluatorKey: 'state_consumer_redressal',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Karnataka',
    approvedDate: new Date('2018-04-10'),
    amendments: 'Advisory on regional bilingual labeling'
  },

  // Tamil Nadu
  {
    ruleId: 'TN-ENF-07',
    ruleNumber: 'Rule 7',
    title: 'Packer Registration under Labour & LM Dept (Tamil Nadu)',
    description: 'Every manufacturing or packing premises in Tamil Nadu must be registered with the Controller of Legal Metrology, Chennai.',
    jurisdiction: 'State',
    stateName: 'Tamil Nadu',
    productCategory: 'All',
    effectiveFrom: new Date('2011-12-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Tamil Nadu Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://labour.tn.gov.in/legalmetrology',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Tamil Nadu',
    approvedDate: new Date('2011-11-10'),
    amendments: 'TN Enforcement Rules notification'
  },

  // Delhi
  {
    ruleId: 'DL-ENF-05',
    ruleNumber: 'Rule 5',
    title: 'Weights & Measures Dept Packer Registration (Delhi)',
    description: 'All manufacturers, packers, and importers in NCT of Delhi must hold registration certificate from Weights & Measures Dept.',
    jurisdiction: 'State',
    stateName: 'Delhi',
    productCategory: 'All',
    effectiveFrom: new Date('2012-01-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Delhi Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://delhi.gov.in/dept-weights-measures',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Weights & Measures, Delhi',
    approvedDate: new Date('2011-12-15'),
    amendments: 'NCT Delhi gazette order'
  },

  // Gujarat
  {
    ruleId: 'GJ-ENF-06',
    ruleNumber: 'Rule 6',
    title: 'Packer License & Registration (Gujarat)',
    description: 'Pre-packaged commodity packers in Gujarat must possess valid registration with the Legal Metrology Division, Gandhinagar.',
    jurisdiction: 'State',
    stateName: 'Gujarat',
    productCategory: 'All',
    effectiveFrom: new Date('2011-06-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Gujarat Legal Metrology (Enforcement) Rules, 2011',
    sourceUrl: 'https://fcs.gujarat.gov.in/legal-metrology',
    lastVerifiedDate: new Date('2024-01-15'),
    version: '1.0',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Gujarat',
    approvedDate: new Date('2011-05-15'),
    amendments: 'Gujarat state enforcement enactment'
  }
];

// 3. Multi-Version Historical, Current, and Future Scheduled Versions
// This preserves complete historical lineages for compliance time-travel audits
const ruleVersions = [
  // --- RULE-06-1-DA (Unit Sale Price) ---
  {
    ruleId: 'RULE-06-1-DA',
    version: '1.0',
    ruleNumber: 'Rule 6(1)(da)',
    title: 'Rule 6(1)(da): Unit Sale Price (USP) [Discretionary Bulk Era]',
    requirement: 'Unit sale price declaration was discretionary under the initial 2011 notification and only recommended for select bulk agricultural commodities exceeding 5 kg/5 L.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: new Date('2021-10-31'),
    status: 'Expired',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Joint Secretary, Ministry of Consumer Affairs, Food & Public Distribution',
    approvedDate: new Date('2011-03-07'),
    amendments: 'Original enactment under GSR 202(E) dated 07.03.2011',
    weight: 10,
    severity: 'LOW',
    evaluatorKey: 'rule06_1_da'
  },
  {
    ruleId: 'RULE-06-1-DA',
    version: '2.0',
    ruleNumber: 'Rule 6(1)(da)',
    title: 'Rule 6(1)(da): Unit Sale Price (USP) [Mandatory Metric Rule]',
    requirement: 'Mandatory declaration of Unit Sale Price (USP) in Rupees per g/ml (for net quantity <= 1kg/1L) or per kg/L (for net quantity > 1kg/1L) or per number on all pre-packaged retail commodities.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2021-11-01'),
    effectiveTo: new Date('2026-12-31'),
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2021',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology, Government of India',
    approvedDate: new Date('2021-11-02'),
    amendments: 'Amended via Gazette Notification G.S.R. 779(E) dated 02.11.2021 (enforced 2021-11-01 / 2022-12-01)',
    weight: 10,
    severity: 'MEDIUM',
    evaluatorKey: 'rule06_1_da'
  },
  {
    ruleId: 'RULE-06-1-DA',
    version: '3.0',
    ruleNumber: 'Rule 6(1)(da)',
    title: 'Rule 6(1)(da): Unit Sale Price (USP) [Digital QR & Dual-Unit Standardization]',
    requirement: 'Mandatory digital QR-linked Unit Sale Price verification with dual metric/sub-metric declaration and standardized price per standardized serving for packaged food and consumer goods.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2027-01-01'),
    effectiveTo: null,
    status: 'Scheduled',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Draft Digital Amendment Rules, 2026',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Central Metrology Advisory Council & Consumer Protection Board',
    approvedDate: new Date('2026-01-15'),
    amendments: 'Draft Gazette Notification G.S.R. 142(E) dated 15.01.2026 scheduled for enforcement from 01.01.2027',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_da'
  },

  // --- RULE-06-1-E (MRP Declaration) ---
  {
    ruleId: 'RULE-06-1-E',
    version: '1.0',
    ruleNumber: 'Rule 6(1)(e)',
    title: 'Rule 6(1)(e): Maximum Retail Price (MRP) [Pre-GST Regime]',
    requirement: 'Retail sale price must be declared as Maximum Retail Price (inclusive of all taxes). Dual pricing permitted for specialized institutional buyers.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: new Date('2017-12-31'),
    status: 'Expired',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Director, Legal Metrology (Ministry of Consumer Affairs)',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Initial enactment GSR 202(E)',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_e'
  },
  {
    ruleId: 'RULE-06-1-E',
    version: '2.0',
    ruleNumber: 'Rule 6(1)(e)',
    title: 'Rule 6(1)(e): Maximum Retail Price (MRP) [Single MRP & ₹ Symbol Mandate]',
    requirement: 'Maximum Retail Price must be declared strictly as "MRP ₹ xx.xx (inclusive of all taxes)". Dual MRP on identical commodities is strictly prohibited.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2018-01-01'),
    effectiveTo: new Date('2026-12-31'),
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Joint Secretary (Legal Metrology), Govt of India',
    approvedDate: new Date('2017-06-23'),
    amendments: 'Amended via G.S.R. 629(E) dated 23.06.2017 with enforcement from 01.01.2018 prohibiting dual pricing',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_e'
  },
  {
    ruleId: 'RULE-06-1-E',
    version: '3.0',
    ruleNumber: 'Rule 6(1)(e)',
    title: 'Rule 6(1)(e): Maximum Retail Price (MRP) [GST Component Breakdown & Dynamic Verification]',
    requirement: 'MRP must be declared with clear electronic GST component transparency and dynamic anti-profiteering verification index on packaged consumer goods.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2027-01-01'),
    effectiveTo: null,
    status: 'Scheduled',
    sourceDocument: 'Legal Metrology (Price Transparency) Amendment Notification, 2026',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'National Consumer Protection Authority & Legal Metrology Council',
    approvedDate: new Date('2026-02-20'),
    amendments: 'Scheduled Gazette Notification G.S.R. 204(E) dated 20.02.2026 for 2027 enforcement',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_e'
  },

  // --- RULE-06-1-C (Net Quantity) ---
  {
    ruleId: 'RULE-06-1-C',
    version: '1.0',
    ruleNumber: 'Rule 6(1)(c)',
    title: 'Rule 6(1)(c): Net Quantity Declaration [Legacy Format]',
    requirement: 'Net quantity in terms of standard metric weight, measure, or number must be stated on packaging without area-proportional font height scale.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: new Date('2022-03-31'),
    status: 'Expired',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Original enactment GSR 202(E)',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_c'
  },
  {
    ruleId: 'RULE-06-1-C',
    version: '2.0',
    ruleNumber: 'Rule 6(1)(c)',
    title: 'Rule 6(1)(c): Net Quantity Declaration [Schedule II Area-Ratio Matrix]',
    requirement: 'Net quantity in terms of standard metric weight, measure, or number must be declared conforming strictly to minimum font height table under Rule 9 and Schedule II.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2022-04-01'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2021',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2021-11-02'),
    amendments: 'Amended via G.S.R. 779(E) dated 02.11.2021 with strict area-ratio minimum font height matrix',
    weight: 20,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_c'
  },

  // --- RULE-06-1-A (Manufacturer Address) ---
  {
    ruleId: 'RULE-06-1-A',
    version: '1.0',
    ruleNumber: 'Rule 6(1)(a)',
    title: 'Rule 6(1)(a): Manufacturer/Packer Address [Basic Postal Standard]',
    requirement: 'Name and postal address of manufacturer or packer.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2011-04-01'),
    effectiveTo: new Date('2017-06-22'),
    status: 'Expired',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2011-03-01'),
    amendments: 'Original enactment GSR 202(E)',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_a'
  },
  {
    ruleId: 'RULE-06-1-A',
    version: '1.1',
    ruleNumber: 'Rule 6(1)(a)',
    title: 'Rule 6(1)(a): Manufacturer/Packer Address [Physical Premises & PIN Code]',
    requirement: 'Name and complete physical premises address of manufacturer, packer, or importer must be declared including state and PIN code.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2017-06-23'),
    effectiveTo: null,
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Joint Secretary (Consumer Affairs), Govt of India',
    approvedDate: new Date('2017-06-23'),
    amendments: 'Amended via G.S.R. 629(E) mandating full premises details, state, and PIN code',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule06_1_a'
  },

  // --- RULE-10 (E-Commerce Declarations) ---
  {
    ruleId: 'RULE-10',
    version: '1.0',
    ruleNumber: 'Rule 10',
    title: 'Rule 10: E-Commerce Marketplace Declarations [Listing Mandate]',
    requirement: 'Digital marketplaces must display all mandatory declarations on product listings prior to purchase.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2017-06-23'),
    effectiveTo: new Date('2026-12-31'),
    status: 'Active',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Director of Legal Metrology',
    approvedDate: new Date('2017-06-23'),
    amendments: 'Introduced vide G.S.R. 629(E) dated 23.06.2017 for digital platforms',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule10'
  },
  {
    ruleId: 'RULE-10',
    version: '2.0',
    ruleNumber: 'Rule 10',
    title: 'Rule 10: E-Commerce Marketplace Declarations [National Repository Real-Time Sync]',
    requirement: 'Mandatory real-time automated API synchronization of e-commerce catalog declarations with the National Legal Metrology Central Repository database.',
    jurisdiction: 'Central',
    stateName: null,
    productCategory: 'All',
    effectiveFrom: new Date('2027-01-01'),
    effectiveTo: null,
    status: 'Scheduled',
    sourceDocument: 'Legal Metrology (E-Commerce Central Registry) Rules, 2026',
    sourceUrl: 'https://consumeraffairs.nic.in/acts-and-rules/legal-metrology/packaged-commodities-rules-2011',
    approvalStatus: 'Approved',
    approvedBy: 'Ministry of Consumer Affairs & IT Council',
    approvedDate: new Date('2026-01-10'),
    amendments: 'Scheduled notification G.S.R. 88(E) dated 10.01.2026',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'rule10'
  },

  // --- TS-ENF-07 (Telangana Packer Registration) ---
  {
    ruleId: 'TS-ENF-07',
    version: '1.0',
    ruleNumber: 'Rule 7(1)',
    title: 'Packer Registration under Controller [Physical Form 1 Era] (Telangana)',
    requirement: 'Manual physical filing of Form 1 packer registration certificate with Controller of Legal Metrology, Hyderabad.',
    jurisdiction: 'State',
    stateName: 'Telangana',
    productCategory: 'All',
    effectiveFrom: new Date('2015-06-02'),
    effectiveTo: new Date('2023-12-31'),
    status: 'Expired',
    sourceDocument: 'Telangana Legal Metrology (Enforcement) Rules, 2015',
    sourceUrl: 'https://tsconsumeraffairs.telangana.gov.in/legal-metrology.jsp',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Govt of Telangana',
    approvedDate: new Date('2015-06-02'),
    amendments: 'Telangana State Bifurcation Enactment under Act 1 of 2014',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration'
  },
  {
    ruleId: 'TS-ENF-07',
    version: '2.0',
    ruleNumber: 'Rule 7(1)',
    title: 'Packer Registration under Controller [TS-iPASS Digital Portal] (Telangana)',
    requirement: 'Mandatory digital registration of pre-packaged commodity packers through TS-iPASS single-window portal under Rule 7.',
    jurisdiction: 'State',
    stateName: 'Telangana',
    productCategory: 'All',
    effectiveFrom: new Date('2024-01-01'),
    effectiveTo: new Date('2026-12-31'),
    status: 'Active',
    sourceDocument: 'Telangana Legal Metrology (Enforcement) Rules, 2015 & TS-iPASS Circular',
    sourceUrl: 'https://tsconsumeraffairs.telangana.gov.in/legal-metrology.jsp',
    approvalStatus: 'Approved',
    approvedBy: 'Controller of Legal Metrology, Govt of Telangana',
    approvedDate: new Date('2023-12-15'),
    amendments: 'G.O.Ms.No. 18 Consumer Affairs & Legal Metrology Dept dated 15.12.2023 transitioning to TS-iPASS',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration'
  },
  {
    ruleId: 'TS-ENF-07',
    version: '2.1',
    ruleNumber: 'Rule 7(1)',
    title: 'Packer Registration under Controller [QR-Linked Certificate Labeling] (Telangana)',
    requirement: 'Mandatory dynamic QR-code certificate embedding on wholesale outer packaging linked to Telangana Legal Metrology portal registration record.',
    jurisdiction: 'State',
    stateName: 'Telangana',
    productCategory: 'All',
    effectiveFrom: new Date('2027-01-01'),
    effectiveTo: null,
    status: 'Scheduled',
    sourceDocument: 'Telangana Legal Metrology (Smart Verification) Notification, 2026',
    sourceUrl: 'https://tsconsumeraffairs.telangana.gov.in/legal-metrology.jsp',
    approvalStatus: 'Approved',
    approvedBy: 'Special Chief Secretary & Controller, Telangana',
    approvedDate: new Date('2026-02-12'),
    amendments: 'Gazette Notification No. TS-LM-2026-04 dated 12.02.2026',
    weight: 15,
    severity: 'HIGH',
    evaluatorKey: 'state_packer_registration'
  }
];

// Helper to fill version list for rules that only have 1 version yet
const allMasterRules = [...centralRules, ...stateRules];
for (const r of allMasterRules) {
  const existing = ruleVersions.find(v => v.ruleId === r.ruleId);
  if (!existing) {
    ruleVersions.push({
      ruleId: r.ruleId,
      version: r.version || '1.0',
      ruleNumber: r.ruleNumber,
      title: r.title,
      requirement: r.description,
      jurisdiction: r.jurisdiction,
      stateName: r.stateName,
      productCategory: r.productCategory || 'All',
      effectiveFrom: r.effectiveFrom || new Date('2011-04-01'),
      effectiveTo: r.effectiveTo || null,
      status: r.status || 'Active',
      sourceDocument: r.sourceDocument,
      sourceUrl: r.sourceUrl,
      approvalStatus: r.approvalStatus || 'Approved',
      approvedBy: r.approvedBy || 'Director of Legal Metrology',
      approvedDate: r.approvedDate || new Date('2011-03-01'),
      amendments: r.amendments || 'Initial statutory notification',
      weight: r.weight || 10,
      severity: r.severity || 'MEDIUM',
      evaluatorKey: r.evaluatorKey
    });
  }
}

/**
 * Seed master rules and all version histories into MongoDB.
 * Never deletes previous versions; preserves every historical snapshot.
 */
const seedRules = async () => {
  try {
    // 1. Seed Rule Master Collection
    let masterUpdated = 0;
    for (const rule of allMasterRules) {
      const res = await Rule.findOneAndUpdate(
        { ruleId: rule.ruleId },
        { $set: rule },
        { upsert: true, new: true }
      );
      if (res) masterUpdated++;
    }

    // 2. Seed RuleVersion Immutable Historical Collection
    let versionsUpdated = 0;
    for (const vDoc of ruleVersions) {
      const res = await RuleVersion.findOneAndUpdate(
        { ruleId: vDoc.ruleId, version: vDoc.version },
        { $set: vDoc },
        { upsert: true, new: true }
      );
      if (res) versionsUpdated++;
    }

    console.log(`Rules and Versions seeded successfully: ${masterUpdated} rules and ${versionsUpdated} version snapshots preserved.`);
    return { success: true, rulesCount: masterUpdated, versionsCount: versionsUpdated };
  } catch (err) {
    console.error('Failed to seed rules & versions:', err);
    throw err;
  }
};

module.exports = {
  seedRules,
  centralRules,
  stateRules,
  ruleVersions
};
